# Generated by Django 3.2.5 on 2021-07-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='Nome',
            field=models.CharField(max_length=194, verbose_name='Nome da Equipe'),
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('Equipes', models.ManyToManyField(to='adm.Equipe')),
            ],
            options={
                'verbose_name': 'Jogos',
                'verbose_name_plural': 'Jogos',
            },
        ),
    ]
