# Generated by Django 3.2.5 on 2021-07-19 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_auto_20210719_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='Perdedora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perdedora', to='adm.equipe', verbose_name='perdedora'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='Vencedora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vencedora', to='adm.equipe', verbose_name='vencedora'),
        ),
    ]
