# Generated by Django 3.2.5 on 2021-07-19 17:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_auto_20210719_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='Nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=194, verbose_name='Nome do Jogo'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fim', models.BooleanField(default=False, verbose_name='Status da partida')),
                ('DataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('Jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jogo', to='adm.jogo', verbose_name='Jogo')),
                ('Perdedora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Equipe_perdedora', to='adm.equipe', verbose_name='Equipe_perdedora')),
                ('Vencedora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Equipe_vencedora', to='adm.equipe', verbose_name='Equipe_vencedora')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
    ]
