# Generated by Django 3.2.5 on 2021-07-19 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_auto_20210719_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QtdRed', models.PositiveIntegerField(verbose_name='Quantidade de 3 vermelhos')),
                ('QtdBlack', models.PositiveIntegerField(verbose_name='Quantidade de 3 pretos')),
                ('QtdCartas', models.PositiveIntegerField(verbose_name='Quantidade de cartas')),
                ('PontosCanastra', models.PositiveIntegerField(verbose_name='Pontos totais de canastra')),
                ('TotalPontos', models.PositiveIntegerField(verbose_name='Pontos totais')),
                ('DataCadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('Equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.partida', verbose_name='Equipe')),
                ('Partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Partida', to='adm.jogo', verbose_name='Partida')),
            ],
            options={
                'verbose_name': 'Rodada',
                'verbose_name_plural': 'Rodadas',
            },
        ),
    ]
