# Generated by Django 3.2.5 on 2021-07-19 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0006_rodada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodada',
            name='Equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.equipe', verbose_name='Equipe'),
        ),
    ]
