# Generated by Django 3.2.5 on 2021-07-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0007_alter_rodada_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodada',
            name='Morto',
            field=models.BooleanField(default=False, verbose_name='Pegou morto'),
        ),
    ]
