# Generated by Django 3.2.5 on 2021-07-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0008_rodada_morto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodada',
            name='Partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Partida', to='adm.partida', verbose_name='Partida'),
        ),
    ]
