# Generated by Django 3.2.5 on 2021-07-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0010_alter_rodada_pontoscanastra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rodada',
            name='TotalPontos',
            field=models.IntegerField(verbose_name='Pontos totais'),
        ),
    ]
